unbind r
bind r source-file ~/.tmux.conf

# configure tmux
set -g prefix C-s
set -g mouse on
set -g default-terminal "tmux-256color"
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g status-position top       # position
set -g set-clipboard on          # use system clipboard
set -g status-interval 2
set -g automatic-rename on
set -g automatic-rename-format "#{pane_current_command}"
set -g renumber-windows on

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# vim-like navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# list of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_status_session_text " #S"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

# left status
set -g status-left-length 120
set -g status-left "#{E:@catppuccin_status_session}"

# right status
set -g status-right-length 120
set -g status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
